#!/usr/bin/env bash

shopt -s extglob # Activate extended patternering features

# Set to true if cleaning process
declare CLEANING_UP=false

# Set true if hook script is used
declare HOOK_USED=false
# Hook variables setted if hook is used
declare HOOK_SCRIPT=""
declare HOOK_ACTION=""

### FUNCTION BEGIN
# Convert size in bytes in human readable size KiB, MiB, GiB...
# ARGUMENTS:
# 	$1 (integer) value in bytes
# OUTPUTS:
# 	Prints value to stdout
### FUNCTION END
hrb() {
    local bytes="$1"
    numfmt --to=iec-i --suffix=O --format="%9.2f" "$bytes" | sed s/'^ *\([0-9,\.]*\)\(.*\)'/'\1 \2'/
}

### FUNCTION BEGIN
# Convert size in human readable size KiO, MiO, GiO to size in bytes numerical ...
# ARGUMENTS:
# 	$1 (string) size in bytes , kiB, ...
# OUTPUTS:
# 	Writes String to STDOUT
### FUNCTION END
bhr() {
    local humanBytes="${1//\./,}i"
    numfmt --from=iec-i "$humanBytes"
}

### FUNCTION BEGIN
# launch cleanup process
# GLOBALS:
# 	CLEANING_UP
#   HOOK_USED
# RETURNS:
#   0 on sucess, non zero otherwise
### FUNCTION END
cleanup() {
    if $CLEANING_UP; then
        return 0
    fi
    CLEANING_UP=true

    local error=false

    # Delete tmp files
    rm -rf "${TMP_DIR}"

    if [[ $(type -t cleanup_method) == function ]]; then
        if ! cleanup_method; then
            log "Error while executing cleanup" error
            error=true
        fi
    fi

    if $HOOK_USED; then
        if ! _launch_hook "${HOOK_SCRIPT}" after "${HOOK_ACTION}"; then
            log "Error when executing after hook '${HOOK_SCRIPT}'"
            error=true
        fi
    fi

    if $error; then
        return 1
    else
        return 0
    fi
}

### FUNCTION BEGIN
# Exit script with cleaning up correctly
# ARGUMENTS:
# 	$1 (string) message to print
#   $2 (integer-optionnal) return code if not use 1 value
# OUTPUTS:
# 	Call log to print message
# RETURNS:
#   exit script with $2 code
### FUNCTION END
abord() {
    local message=$1
    local -i exit_code=${2:-1}
    log "$message" error
    cleanup
    exit $exit_code
}

_launch_hook() {
    local script_file="$1"
    local hook="$2"   # before | after
    local action="$3" # backup | restore

    if [[ ! -f $script_file || ! -x $script_file ]]; then
        abord "Hook file '$script_file' is not an executable file !"
    fi
    log "Launch hook ${hook} ${action} '${script_file}'" verbose
    if ! log_cmd "${script_file}" "${hook}" "${action}" "${ARGS[@]}"; then
        return 1
    fi
}

init_hook() {
    # Avoid calling init_hook multiple times
    if $HOOK_USED; then
        return 0
    fi

    HOOK_SCRIPT="$1"
    HOOK_ACTION="$2"

    if ! _launch_hook "${HOOK_SCRIPT}" before "${HOOK_ACTION}"; then
        abord "Error when executing before hook '${HOOK_SCRIPT}'"
    fi
    HOOK_USED=true

    return 0
}

handle_sigterm_sigint() {
    abord 'Script interrupted, clean properly'
}

is_archive_exists() {
    local name="$1"
    if [[ -z "$name" ]]; then
        abord "archive name is required"
    fi

    list_archives | grep -Eq "^${name}(\.base|\.inc[0-9]+)?$"
    return $?
}

### FUNCTION BEGIN
# Get archive infos. Infos as to be printed with this format:
# Name: <archive name>
# Size: <size in bytes>
# Timestamp: <date as timestamp>
# Increments: <number of increments>
# Increments names: <list of increments names separated by commas>
# Increments sizes: <list of increments sizes in bytes separated by commas>
# Increments timestamps: <list of increments dates as timestamp separated by commas>
# GLOBALS:
#   LOCAL_REPO destination dir for archives
# ARGUMENTS:
#   $1 : name of the archive the name can be an increment name
# OUTPUTS:
# 	Print infos
# RETURNS:
#   0 on success, 1 if archive not found
### FUNCTION END
get_archive_infos() {
    local name="$1"
    local human_readable="${2:-false}"

    if [[ -z "$name" ]]; then
        abord "archive name is required"
    fi

    # Delete .base or .incX suffix to get the main archive name
    # This command requires extglob to be enabled (shopt -s extglob)
    name="${name%.@(base|inc+([0-9]))}"

    local archive_list=""
    # shellcheck disable=SC2086
    archive_list=$(list_archives false true false | sed '1d' | grep -E "^${name}(\.base|\.inc[0-9]+)?[[:space:]]" | sort)

    if [[ -z "$archive_list" ]]; then
        return 1
    fi

    local is_incremental=false
    if echo "$archive_list" | grep -q '.base'; then
        is_incremental=true
    fi

    local size=0
    local timestamp=0

    local timestamp_title="Timestamp"
    $human_readable && timestamp_title="Date"

    size=$(awk '{sum += $2} END {print sum}' <<<"$archive_list")
    timestamp=$(echo "$archive_list" | grep -v '.inc' | head -n1 | cut -f3)

    if $human_readable; then
        size=$(hrb "${size}")
        timestamp=$(date -d "@${timestamp}")
    fi

    cat <<GLOBAL_INFOS
Name: ${name}
Size: ${size}
${timestamp_title}: ${timestamp}
GLOBAL_INFOS

    if $is_incremental; then
        echo "Incremental backup"
        echo "Details:"
        printf "%-10s\t%-10s\t%s\n" "Name" "Size" "$timestamp_title"

        while read -r name size timestamp; do
            if $human_readable; then
                size=$(hrb "${size}")
                timestamp=$(date -d "@${timestamp}")
            fi
            # Afficher les infos formatées
            printf "%-10s\t%-10s\t%s\n" "$name" "$size" "$timestamp"
        done <<<"$archive_list"
    fi

    return 0
}

get_last_incremental_backup_name() {
    local name="$1"
    if [[ -z "$name" ]]; then
        abord "archive name is required"
    fi

    # Delete .base or .incX suffix to get the main archive name
    # This command requires extglob to be enabled (shopt -s extglob)
    name="${name%.@(base|inc+([0-9]))}"

    # List archives only archives names, filter on the given name, sort them and get the last one
    local output
    output=$(list_archives | grep "^${name}.inc[0-9][0-9]*" | sort | tail -n1)
    echo "${output}"
}

### FUNCTION BEGIN
# Get list of archives to fetch based on given name and increments
# ARGUMENTS:
#   $1 : name of the archive the name can be an increment name
#   $2 : increments to fetch (all|base|<number>) default all
# OUTPUTS:
# 	Print list of archives to fetch
### FUNCTION END
get_archives_to_fetch() {
    local name="$1"
    local increments="${2-all}"

    if [[ ! "$increments" =~ ^(all|base|[0-9]+)$ ]]; then
        abord "Increment value '${increments}' invalid"
    fi

    # Delete .base or .incX suffix to get the main archive name
    # This command requires extglob to be enabled (shopt -s extglob)
    name="${name%.@(base|inc+([0-9]))}"

    local list_archives=""
    list_archives=$(list_archives | grep "^${name}" | sort)

    if [[ -z $list_archives ]]; then
        return
    fi

    if [[ $increments == 'all' ]]; then
        echo "$list_archives"
        return
    fi

    if [[ $increments == 'base' ]]; then
        echo "$list_archives" | grep ".base" | tail -n1
        return
    fi

    local max_increment=""
    max_increment=$(printf "%02d" $((10#$increments)))

    if ! echo "$list_archives" | grep -q ".inc${max_increment}"; then
        abord "Increment number '${increments}' doesn't exist for archive '${name}'"
    fi

    while read -r archive_name; do
        if [[ "$archive_name" == *".base" ]]; then
            echo "$archive_name"
            continue
        fi

        local increment_number=${archive_name##*.inc}
        if [[ ! "$increment_number" =~ ^[0-9]{1,2}$ ]]; then
            continue
        fi

        if [[ $increment_number -le $max_increment ]]; then
            echo "$archive_name"
            continue
        fi
    done < <(echo "$list_archives")
}

restore_an_archive() {
    local name="$1"
    local destination="$2"

    if [[ -z "$name" ]]; then
        abord "archive name is required"
    fi
    if [[ -z "$destination" ]]; then
        abord "destination directory is required"
    fi

    log "Fetching archive '${name}' ..." info
    if ! fetch_from_dest --name="$name" --destination="$TMP_DIR"; then
        abord "Error while fetching archive"
    fi
    log "archive fetched" success

    log "Check archive '${name}' ..." info
    local actual_path
    actual_path=$(pwd)

    local md5_file="${name}.md5"

    cd "${TMP_DIR}" || abord "Cannot change directory to '${TMP_DIR}'"

    if ! log_cmd md5sum --check "$md5_file"; then
        abord "Archive check failed, files are corrupted"
    fi
    log "Archive checked " success
    cd "$actual_path" || abord "Cannot change directory to '${actual_path}'"

    local verbose_cmd=""
    [[ "${LOG_VERBOSE:-false}" == "true" ]] && verbose_cmd="--verbose"

    # Check if we have an incremental backup
    local incremental_cmd=()
    if [[ "$name" =~ \.(inc[0-9]{2}|base)$ ]]; then
        local snar_file="${TMP_DIR}/${name}.snar"
        if [[ ! -f "$snar_file" ]]; then
            abord "Snar file '${snar_file}' not found for incremental restore"
        fi

        incremental_cmd=(--listed-incremental="${snar_file}")
    fi

    for tar_file in "$TMP_DIR/${name}".tar*; do
        [[ -e "$tar_file" ]] || continue
        log "Restore archive file '${tar_file}..." info
        if ! log_cmd tar --extract --file="${tar_file}" --auto-compress ${verbose_cmd} "${incremental_cmd[@]}" --directory="${destination}" .; then
            abord "Cannot restore archive '${tar_file}' !"
        fi
        log "Archive file '${tar_file} restored" success
    done

    log "Checking extracted files..." info
    local md5_content_file="${TMP_DIR}/${name}.content.md5"
    cd "${destination}" || abord "Cannot change directory to '${destination}'"

    if [[ ! -s "$md5_content_file" ]]; then
        log "Content md5 file '${md5_content_file}' not found or empty (no files to check)" warning
    elif ! log_cmd md5sum --check "$md5_content_file"; then
        abord "Restored files check failed, files are corrupted"
    fi
    log "Restored files checked" success
}
